### ISSUE TITLE
Syntax error on Python 3.5.6

### ISSUE THREAD

**Issue by stsievert** [nextml/caption-contest-data#34]
``` python
>>> import caption_contest_data as ccd
```

throws a syntax error on line 90 of `_api.py` with this code:

``` python
ints: List[Union[str, int]] = [int(c) if c.isnumeric() else c.split("-")[0] for c in _ints]
```

**Comment by stsievert** [comment]
``` shell
$ conda create -n py35 python=3.5 numpy pandas scipy
$ conda activate py35
$ python
>>> import caption_contest_data as ccd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scott/anaconda3/envs/py35/lib/python3.5/site-packages/caption_contest_data/__init__.py", line 3, in <module>
    from ._api import metadata, refresh, responses, summary, summary_ids
  File "/Users/scott/anaconda3/envs/py35/lib/python3.5/site-packages/caption_contest_data/_api.py", line 90
    ints: List[Union[str, int]] = [
        ^
SyntaxError: invalid syntax
```
