### ISSUE TITLE
What should the `CCD_IP` be set to?

### ISSUE THREAD

**Issue by jingweiz** [nextml/caption-contest-data#4]
```
python download_dashboards.py 
Traceback (most recent call last):
  File "/usr/local/google/home/zhangjingwei/nycc/caption-contest-data/download_dashboards.py", line 14, in <module>
    CCD_IP = os.environ["CCD_IP"]
             ~~~~~~~~~~^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'CCD_IP'
```
Thanks!

**Comment by stsievert** [comment]
All the data is available at https://nextml.github.io/caption-contest-data/
